MozillaReality/unity-webxr-export

Assets/WebVR/Prefabs/WebVRCameraSet.prefab
=> Removing light and fixing audio listeners

README.md
@cvan we'll need to update webvr.rocks with the latest browser support info.  esp in regards to Windows MR.
=> adds compatibility info

CONTROLLERS.md
Fix #75 
@caseyyee or @cvan , can you help me testing Oculus controllers? Use the snippet I put in the bug to create a table similar to what I did with VIVE or paste me the output after pressing and touching all the buttons (indicating the interaction you were doing when running the snippet).
=> [WIP] Documenting input

Assets/WebGLTemplates/WebVR/index.html
=> Remove the loader when loading is complete.

Assets/WebGLTemplates/WebVR/webvr.js, Assets/WebVR/Scripts/WebVRCamera.cs
=> Now not capturing keys to avoid conflicting with the developer's code

README.md
=> Documenting Chrome WebVR Origin Trial

Assets/WebGLTemplates/WebVR/index.html, Assets/WebGLTemplates/WebVR/webvr.js
=> Resize function now invoked after finishing loading.

README.md
check out https://github.com/mozilla/unity-webvr-export/compare/master...readme-demo-link-tweaks?quick_pull=1&short_path=04c6e90#diff-04c6e90faac2675aa89e2176d2eec7d8 and https://github.com/mozilla/unity-webvr-export/blob/d6c50330638d261fd8323e490b9dd48340742f7f/README.md#readme
=> have GIF link to demo; tweak Demo heading

Assets/WebVR/Scripts/WebVRCamera.cs
=> Enable VR controllers in Editors mode

docs/troubleshooting-faq.md
Fixes https://github.com/mozilla/unity-webvr-export/issues/149
=> Adds Why Unity

Assets/WebGLTemplates/WebVR/webvr.js
fixes https://github.com/mozilla/unity-webvr-export/issues/179
=> removes duplicate handling of Unity loading

Assets/WebGLTemplates/WebVR/index.html, Assets/WebGLTemplates/WebVR/lib/telemetry.js, Assets/WebGLTemplates/WebVR/webvr.js
Fix #170
Added measurements for getting and parsing the UnityLoader and the scene
load.
=> Adding performance measurement infrastructure.

Assets/WebVR/Scripts/WebVRCamera.cs
=> Removed a duplicated global to local transformation

Assets/WebVR/Scenes/WebVR.unity
=> Re-attaching hand objects to the camera rig.

Assets/WebGLTemplates/WebVR/lib/telemetry.js, Build/lib/telemetry.js
@delapuente: okay, one more time - let's see if I can get this right…
this reminds me we're going to need to start adding tests (#133) soon :smile:
👍thanks for your help! (I want to get this one fixed correctly so we can stop improperly logging traffic and JS errors for local environments before I tag `v1.2.0` [I will update PR #239 after we get this figured out].)
=> improve origin check in `telemetry.js` (follow up to PR #236 and issue #223)

Assets/WebVR/Scenes/WebVR.unity
=> Adding mesh collider to the desert to prevent objects from falling through

Assets/WebVR/Scripts/WebVRManager.cs
=> Allow toggling VR with WebGL only, Fixes Issue #278

README.md, docs/troubleshooting-faq.md
readme:
https://github.com/caseyyee/unity-webvr-export/blob/72aef6c2504ab3b7828dd82c237542b585326f95/README.md
faq:
https://github.com/caseyyee/unity-webvr-export/blob/72aef6c2504ab3b7828dd82c237542b585326f95/docs/troubleshooting-faq.md
=> Adds/updates VR testing.

docs/controllers.md, docs/project-setup.md
https://github.com/caseyyee/unity-webvr-export/blob/88097a4d539cf0e7fc1e06718d23794d2af9b47d/docs/project-setup.md
https://github.com/caseyyee/unity-webvr-export/blob/88097a4d539cf0e7fc1e06718d23794d2af9b47d/docs/controllers.md
=> Getting started options and Input Manager settings.

README.md
From Jump Games for early exploration and testing.
=> Adds credit for Anthony Palma

Assets/WebGLTemplates/WebVR/index.html, Assets/WebGLTemplates/WebVR/styles/webvr.css, Assets/WebGLTemplates/WebVR/webvr.js, Assets/WebVR/Plugins/WebGL/webvr.jslib, Assets/WebVR/Scripts/WebVRCamera.cs, Assets/WebVR/Scripts/WebVRManager.cs, Assets/WebVR/Scripts/WebVRUI.cs
Some of the changes:
- Changes enter VR logic
- Headset pose data uses shared array
- Removes unused latency checks
- Removes controller status (with changes to API, we cannot sniff out controllers before entering VR)
- Fixes some CSS styling.
Also fixes:
https://github.com/mozilla/unity-webvr-export/issues/256
Tested with:
- Oculus Rift, win 10, Firefox, Firefox Nightly
- Oculus Rift, win 10, Chrome Canary
- Oculus Browser, Oculus Go
- Firefox Reality, Oculus
=> Refactors webvr.js

Assets/WebVR/Scripts/WebVRController.cs, Assets/WebVR/Scripts/WebVRMatrixUtil.cs
Adds arm model to 3dof controllers.
=> Adds arm model for 3dof controllers

Assets/WebGLTemplates/WebXR/webxr.js, Build/webxr.js
Solves potential issues when ending Immersive Session.
Solves issues with Polyfill.
=> Inline Session support

Assets/Plugins.meta, Assets/WebXR/Scripts/WebXRController.cs
Resolves issues #348 and #382 
Also removed a meta file of non existing folder
=> WebXRController to set local pose instead of world pose

Assets/WebXR/Samples/Desert/Scripts/DesertFreeFlightController.cs
Dragging the pointer on non immersive mode didn't work well on mobile and other no mouse devices. Added support for touch.
Only C# changes. Need to rebuild the project.
=> Sample flightcontroller touch support

Assets/WebXR/Scripts/WebXRCamera.cs, Assets/WebXR/Scripts/WebXRController.cs, docs/xr-testing.md
Edited the WebXRCamera.cs and WebXRController.cs scripts to work with modern XR plugin management (non-legacy).
Also updated the readme for In-Editor VR testing.
=> Updated to work with XR plugin management (non-legacy) 
